### ISSUE TITLE
Keep track of total amount staked on posts

### ISSUE THREAD

**Issue by JakeHartnell** [public-awesome/stakewatcher#37]
In order to implement a feature where we sort by most staked on post, we need to keep track of the `total_amount_staked` on posts, similar to how we keep track of `total_votes` or `total_votes_amount`.

**Comment by jhernandezb** [comment]
total amount staked over time or total amount staked at current time?

**Comment by JakeHartnell** [comment]
> total amount staked over time or total amount staked at current time?

Hmmm, would lean towards current time, but might be best to do both if it's not too hard? What do you think @shanev?

**Comment by shanev** [comment]
Staked for current time I think makes most sense to me. So the posts that are most valuable will stay at the top. It gives content a real-time valuation, which is pretty cool.
